spring: 
 profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: eureka-server-high
#开启权限认证
  security: 
    basic:
      enabled: true
    user:
      name: root
      password: root

server:
  host: 123.57.207.4
  port: 7001
eureka:
  client:
    #此项目不作为客户端注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@123.57.207.4:7001/eureka,http://${spring.security.user.name}:${spring.security.user.password}@123.57.207.4:7002/eureka
---
spring:
  profiles: test
  application:
    name: eureka-server-high
#开启权限认证
  security: 
    basic:
      enabled: true
    user:
      name: root
      password: root

server:
  host: localhost
  port: 8762
eureka:
  client:
    #此项目不作为客户端注册
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${server.host}:${server.port}/eureka