spring:
  profiles:
    active: dev1
  application:
    name: eureka-server-high
  security: 
    basic:
      enabled: true
    user:
      name: root
      password: root
dev:
  host: localhost
  dev1Port: 8761
  dev2Port: 8762
  dev3Port: 8763