spring:
  application:
    name: config-server
  security: 
    basic:
      enabled: true
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lingfengzx/WLC_config_center
server:
  port: 3344