spring:
  application:
    name: config-server
  security: 
    basic:
      enabled: true
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lingfengzx/WLC_config_center
  rabbitmq:
    host: 123.56.110.16    #公网地址
    port: 15672
    username: admin
    password: admin
server:
  port: 3344

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@123.57.207.4:7001/eureka,http://root:root@123.57.207.4:7002/eureka
  instance:
    prefer-ip-address: true #当猜测主机名时，服务器的IP地址应该在操作系统报告的主机名中使用