spring:
  application:
    name: auth-server
  redis:
    database: 2
    host: 123.56.110.16
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 7011

management:
  endpoint:
    health:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@123.57.207.4:7001/eureka,http://root:root@123.57.207.4:7002/eureka
