spring:
  application:
    name: auth-server

server:
  port: 7011

management:
  endpoint:
    health:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@123.57.207.4:7001/eureka,http://root:root@123.57.207.4:7002/eureka
