spring:
  thymeleaf:
    cache: false 
    mode: HTML5 
    encoding: UTF-8 
    servlet: 
      content-type: text/html 
      prefix: classpath:/templates 
      suffix: .html
  application:
    name: consumer-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/wlc?useUnicode=true&characterEncoding=utf-8
    username : root
    password : 
    
server:
  port: 8079
  
  
eurekaServer:
  host: localhost
  port: 8085
  user: root
  password: root

eureka:
  client:
    #将此项目注册到Eureka服务
    register-with-eureka: true
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/EurekaHighServer/eureka
      #defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
      
feign:
  hystrix:
    enabled: true